import type { Locale } from "../../i18n";

export type AtlasCopy = {
  meta: { title: string; description: string };
  nav: string[]; back: string; language: string; theme: string; dark: string; light: string; signature: string;
  hero: { eyebrow: string; title: string; copy: string; primary: string; secondary: string; demo: string };
  proof: string[]; sections: Record<string, { eyebrow: string; title: string; copy: string }>;
  modules: Array<[string, string]>; flow: Array<[string, string]>; governance: Array<[string, string]>; faq: Array<[string, string]>;
  cta: { title: string; copy: string; whatsapp: string; email: string };
};

export const atlasContent: Record<Locale, AtlasCopy> = {
  es: {
    meta: { title: "Nexo | Portal inteligente para proveedores", description: "Nexo reúne documentos, facturas, pagos, devoluciones y cumplimiento en un portal B2B de SOMA." },
    nav: ["Módulos", "Flujo", "Demo", "Gobierno", "Preguntas"], back: "Volver a SOMA", language: "Cambiar idioma", theme: "Cambiar tema", dark: "Modo oscuro", light: "Modo claro", signature: "Una solución de SOMA",
    hero: { eyebrow: "RELACIONES DE PROVEEDORES CONECTADAS", title: "Su red de proveedores, en un solo lugar.", copy: "Nexo reúne documentos, facturas, pagos y cumplimiento para que cada relación comercial avance con claridad y trazabilidad.", primary: "Solicitar demostración", secondary: "Escribir por correo", demo: "Explorar demo" },
    proof: ["Facturas y pagos", "Documentos vigentes", "Devoluciones", "Cumplimiento"],
    sections: {
      modules: { eyebrow: "UNA PLATAFORMA", title: "Cada documento, pago y compromiso conectado.", copy: "Nexo ordena la información que una organización y sus proveedores necesitan para avanzar sin correos dispersos ni hojas de cálculo paralelas." },
      flow: { eyebrow: "FLUJO DE PROVEEDORES", title: "De la validación al pago, con contexto completo.", copy: "Cada etapa conserva responsables, fechas, documentos y evidencias para que la relación comercial sea más simple de gestionar." },
      demo: { eyebrow: "PRODUCTO EN ACCIÓN", title: "Explore cómo trabaja Nexo.", copy: "Demo frontend basada en los flujos de un portal de proveedores. Todos los datos son ficticios." },
      governance: { eyebrow: "CONTROL Y CONFIANZA", title: "Información confiable para cada relación.", copy: "Los equipos y proveedores ven lo que necesitan, con documentos verificables e historial de actividad." },
      faq: { eyebrow: "PREGUNTAS FRECUENTES", title: "Lo esencial antes de implementar.", copy: "Nexo se configura para el proceso documental, financiero y de cumplimiento de cada organización." }
    },
    modules: [["Facturas", "Consulta, estado, vencimientos y documentos asociados en un solo lugar."], ["Pagos", "Programación, detalle y soporte de pagos para cada proveedor."], ["Devoluciones", "Seguimiento claro de solicitudes, causas, valores y resolución."], ["Certificados", "Documentos tributarios disponibles de forma ordenada y descargable."], ["Cumplimiento", "Validación documental y alertas para mantener expedientes al día."], ["Perfil y analítica", "Datos de la organización, contactos y resumen de actividad comercial."]],
    flow: [["Registrar", "El proveedor completa sus datos y carga documentos."], ["Validar", "El equipo revisa requisitos y vigencias."], ["Facturar", "Los documentos comerciales se concentran y consultan."], ["Programar", "Los pagos y novedades se hacen visibles."], ["Acompañar", "La relación conserva historial, certificados y trazabilidad."]],
    governance: [["Acceso por perfil", "Cada persona recibe una vista acorde a su responsabilidad."], ["Documentos vigentes", "Estados y fechas facilitan el seguimiento de requisitos."], ["Historial visible", "Los cambios y movimientos permanecen asociados al registro."], ["Datos protegidos", "La configuración final se alinea con las políticas de cada organización."]],
    faq: [["¿Nexo sirve para cualquier tipo de proveedor?", "Sí. Se adapta a proveedores de productos, servicios, contratistas y aliados según los documentos y flujos requeridos."], ["¿Podemos empezar por facturas y pagos?", "Sí. La implementación puede iniciar por los módulos prioritarios y evolucionar por etapas."], ["¿Los proveedores pueden actualizar sus datos?", "Nexo permite organizar la actualización documental y definir los controles de validación necesarios."], ["¿Esta demo guarda información?", "No. Funciona solo en el navegador con datos ficticios y se reinicia al recargar."], ["¿Cómo solicito una demostración privada?", "Escríbanos por WhatsApp o correo para preparar un recorrido basado en su operación."]],
    cta: { title: "Conecte la relación con sus proveedores.", copy: "Cuéntenos cómo gestionan hoy documentos, facturas y pagos. Diseñaremos una demostración de Nexo alrededor de su proceso.", whatsapp: "Solicitar por WhatsApp", email: "contacto@somacoretech.com" }
  },
  en: {
    meta: { title: "Nexo | Intelligent supplier portal", description: "Nexo brings documents, invoices, payments, returns and compliance together in a SOMA B2B supplier portal." },
    nav: ["Modules", "Workflow", "Demo", "Governance", "Questions"], back: "Back to SOMA", language: "Change language", theme: "Change theme", dark: "Dark mode", light: "Light mode", signature: "A SOMA solution",
    hero: { eyebrow: "CONNECTED SUPPLIER RELATIONSHIPS", title: "Your supplier network, in one place.", copy: "Nexo brings documents, invoices, payments and compliance together so every commercial relationship can move forward with clarity and traceability.", primary: "Request a demo", secondary: "Email us", demo: "Explore demo" },
    proof: ["Invoices and payments", "Current documents", "Returns", "Compliance"],
    sections: { modules: { eyebrow: "ONE PLATFORM", title: "Every document, payment and commitment connected.", copy: "Nexo organizes the information organizations and suppliers need to work without scattered emails or parallel spreadsheets." }, flow: { eyebrow: "SUPPLIER WORKFLOW", title: "From validation to payment, with complete context.", copy: "Every stage keeps owners, dates, documents and evidence so commercial relationships are easier to manage." }, demo: { eyebrow: "PRODUCT IN ACTION", title: "Explore how Nexo works.", copy: "Frontend demo based on supplier portal flows. All data is fictional." }, governance: { eyebrow: "CONTROL AND TRUST", title: "Reliable information for every relationship.", copy: "Teams and suppliers see what they need, with verifiable documents and activity history." }, faq: { eyebrow: "FREQUENTLY ASKED QUESTIONS", title: "The essentials before implementation.", copy: "Nexo is configured around every organization’s document, finance and compliance process." } },
    modules: [["Invoices", "Review status, due dates and supporting documents in one place."], ["Payments", "Schedules, details and payment support for every supplier."], ["Returns", "Clear tracking of requests, reasons, values and resolution."], ["Certificates", "Tax documents organized and ready to download."], ["Compliance", "Document validation and alerts that keep records current."], ["Profile and analytics", "Organization data, contacts and commercial activity at a glance."]],
    flow: [["Register", "Suppliers complete their details and upload documents."], ["Validate", "Teams review requirements and validity dates."], ["Invoice", "Commercial documents are centralized and easy to consult."], ["Schedule", "Payments and updates become visible."], ["Support", "The relationship keeps history, certificates and traceability."]],
    governance: [["Role-based access", "Each person receives a view that matches their responsibility."], ["Current documents", "Statuses and dates make requirement tracking easier."], ["Visible history", "Changes and movements remain attached to every record."], ["Protected data", "Final setup aligns with each organization’s policies."]],
    faq: [["Does Nexo work for every supplier type?", "Yes. It adapts to product suppliers, service providers, contractors and partners based on required documents and workflows."], ["Can we start with invoices and payments?", "Yes. Implementation can begin with priority modules and evolve in stages."], ["Can suppliers update their information?", "Nexo organizes document updates and supports the validation controls each organization needs."], ["Does this demo save data?", "No. It only runs in the browser with fictional data and resets on refresh."], ["How can I request a private demo?", "Message us on WhatsApp or email us so we can prepare a walkthrough around your operation."]],
    cta: { title: "Connect every supplier relationship.", copy: "Tell us how you currently handle documents, invoices and payments. We will design a Nexo demo around your process.", whatsapp: "Request on WhatsApp", email: "contacto@somacoretech.com" }
  }
};
