import { useMemo, useState } from "react";
import { Bell, Building2, ChevronRight, CircleDollarSign, FileCheck2, FileText, Menu, RotateCcw, Search, ShieldCheck, UserRound, X } from "lucide-react";
import type { Locale } from "../../../i18n";
import { certificates, complianceDocuments, invoices, payments, returns, type Invoice, type Payment, type ReturnRecord } from "../atlasDemoData";
import "./atlasDemo.css";

type AtlasModule = "dashboard" | "invoices" | "payments" | "returns" | "certificates" | "profile" | "compliance";
type Detail = Invoice | Payment | ReturnRecord;
const nav: Array<[AtlasModule, string, typeof FileText]> = [["dashboard", "Inicio", Building2], ["invoices", "Facturas", FileText], ["payments", "Pagos", CircleDollarSign], ["returns", "Devoluciones", RotateCcw], ["certificates", "Certificados", FileCheck2], ["profile", "Perfil", UserRound], ["compliance", "Cumplimiento", ShieldCheck]];

export default function AtlasDemo({ locale }: { locale: Locale }) {
  const [module, setModule] = useState<AtlasModule>("dashboard");
  const [query, setQuery] = useState("");
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [dark, setDark] = useState(false);
  const [notice, setNotice] = useState("");
  const labels = locale === "es" ? { demo: "Entorno demostrativo · Datos ficticios", reset: "Reiniciar", search: "Buscar por proveedor o documento", activity: "Actividad reciente", documents: "Documentos al día", scheduled: "Pagos previstos", review: "Facturas en revisión", returns: "Devoluciones abiertas" } : { demo: "Demo environment · Fictional data", reset: "Reset", search: "Search supplier or document", activity: "Recent activity", documents: "Current documents", scheduled: "Upcoming payments", review: "Invoices under review", returns: "Open returns" };
  const records = module === "invoices" ? invoices : module === "payments" ? payments : returns;
  const filtered = useMemo(() => records.filter(row => Object.values(row).join(" ").toLowerCase().includes(query.toLowerCase())), [records, query]);
  const change = (next: AtlasModule) => { setModule(next); setQuery(""); setMobileNavOpen(false); setNotice(`${nav.find(([id]) => id === next)?.[1]} abierto`); };
  return <div className={`atlas-demo-shell ${dark ? "atlas-demo-dark" : ""}`}>
    <div className="atlas-demo-notice"><span>{labels.demo}</span><button onClick={() => { setModule("dashboard"); setQuery(""); setNotice("Demo reiniciada"); }}>{labels.reset}</button></div>
    <div className="atlas-demo-app"><aside className={`atlas-demo-sidebar ${mobileNavOpen ? "open" : ""}`}><div className="atlas-demo-logo"><img src="/nexo-bee-hd.webp" alt=""/><span>NEXO<small>SUPPLIER PORTAL</small></span><button onClick={() => setMobileNavOpen(false)} aria-label="Cerrar menú"><X size={18}/></button></div><nav>{nav.map(([id, label, Icon]) => <button key={id} className={module === id ? "active" : ""} onClick={() => change(id)}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="atlas-demo-side-foot"><span>Red de proveedores</span><b>Organización demo</b></div></aside>{mobileNavOpen && <button className="atlas-demo-backdrop" aria-label="Cerrar navegación" onClick={() => setMobileNavOpen(false)}/>}<section className="atlas-demo-main"><header className="atlas-demo-header"><button className="atlas-demo-mobile-menu" onClick={() => setMobileNavOpen(true)} aria-label="Abrir navegación"><Menu size={20}/></button><div><p>Nexo / {nav.find(([id]) => id === module)?.[1]}</p><h3>{module === "dashboard" ? "Resumen de la relación" : nav.find(([id]) => id === module)?.[1]}</h3></div><div className="atlas-demo-header-actions"><button onClick={() => setDark(!dark)}>{dark ? "Claro" : "Oscuro"}</button><button aria-label="Notificaciones"><Bell size={18}/></button><span>AM</span></div></header><div className="atlas-demo-content" aria-live="polite">{notice && <p className="atlas-demo-live">{notice}</p>}{module === "dashboard" ? <Dashboard labels={labels} onOpen={change}/> : module === "certificates" ? <Certificates/> : module === "profile" ? <Profile/> : module === "compliance" ? <Compliance/> : <Workspace module={module} rows={filtered} query={query} setQuery={setQuery} setDetail={setDetail} labels={labels}/>}</div></section></div>{detail && <DetailModal detail={detail} close={() => setDetail(null)} />}</div>;
}

function Dashboard({ labels, onOpen }: { labels: Record<string, string>; onOpen: (module: AtlasModule) => void }) { return <><div className="atlas-demo-metrics"><Metric label={labels.documents} value="94.8%" trend="+4 este mes"/><Metric label={labels.scheduled} value="$ 13.5M" trend="3 programados"/><Metric label={labels.review} value="01" trend="Requiere validación"/><Metric label={labels.returns} value="02" trend="1 en análisis"/></div><div className="atlas-demo-grid"><article className="atlas-demo-activity"><div><h4>{labels.activity}</h4><button onClick={() => onOpen("invoices")}>Ver facturas <ChevronRight size={15}/></button></div>{["Factura FAC-2094 recibida para validación", "Pago PAG-0841 programado para el 26 de septiembre", "Documento de cumplimiento próximo a vencer"].map((item, i) => <p key={item}><span>0{i + 1}</span>{item}<small>{i === 0 ? "Hace 24 min" : i === 1 ? "Hoy" : "Hace 2 días"}</small></p>)}</article><article className="atlas-demo-status"><span>ESTADO DOCUMENTAL</span><strong>Todo bajo control</strong><p>Dos documentos requieren seguimiento durante este mes.</p><div><i/><i/><i/><i/><i/></div></article></div></>; }
function Metric({ label, value, trend }: { label: string; value: string; trend: string }) { return <article><span>{label}</span><strong>{value}</strong><small>{trend}</small></article>; }
function Workspace({ module, rows, query, setQuery, setDetail, labels }: { module: AtlasModule; rows: Detail[]; query: string; setQuery: (value: string) => void; setDetail: (row: Detail) => void; labels: Record<string, string> }) { const cols = module === "invoices" ? ["Documento", "Proveedor", "Emisión", "Vencimiento", "Valor", "Estado"] : module === "payments" ? ["Pago", "Proveedor", "Fecha", "Valor", "Estado"] : ["Solicitud", "Proveedor", "Motivo", "Valor", "Estado"]; return <><div className="atlas-demo-toolbar"><label><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder={labels.search}/></label><button onClick={() => setQuery("")}>Limpiar</button></div><div className="atlas-demo-table-wrap"><table><thead><tr>{cols.map(col => <th key={col}>{col}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id} onClick={() => setDetail(row)}><td><b>{row.id}</b></td><td>{row.supplier}</td>{"issued" in row && <td>{row.issued}</td>}{"due" in row && <td>{row.due}</td>}{"date" in row && <td>{row.date}</td>}{"reason" in row && <td>{row.reason}</td>}<td>{row.amount}</td><td><span className={`atlas-status ${row.status.toLowerCase().replaceAll(" ", "-")}`}>{row.status}</span></td></tr>)}</tbody></table>{!rows.length && <p className="atlas-demo-empty">No hay resultados para esta búsqueda.</p>}</div></>; }
function Certificates() { return <div className="atlas-demo-cards">{certificates.map(item => <article key={item.title}><FileCheck2/><span>{item.status}</span><h4>{item.title}</h4><p>{item.period}</p><button>Descargar PDF</button></article>)}</div>; }
function Profile() { return <div className="atlas-demo-profile"><article><span>ORGANIZACIÓN</span><h4>Nexo Suministros</h4><p>Información general, contactos y canales de notificación centralizados.</p><button>Editar información</button></article><article><span>CONTACTO PRINCIPAL</span><h4>Gestión comercial</h4><p>Canal configurado para notificaciones documentales y financieras.</p><button>Gestionar contactos</button></article></div>; }
function Compliance() { return <div className="atlas-demo-compliance"><div><h4>Documentación y cumplimiento</h4><p>Revise vigencias y complete los requisitos pendientes.</p></div>{complianceDocuments.map(item => <article key={item.title}><ShieldCheck/><div><b>{item.title}</b><span>{item.expires}</span></div><em className={item.status === "Vigente" ? "ok" : "warn"}>{item.status}</em><button>Ver documento</button></article>)}</div>; }
function DetailModal({ detail, close }: { detail: Detail; close: () => void }) { return <div className="atlas-demo-modal-backdrop" role="presentation" onMouseDown={close}><article className="atlas-demo-modal" role="dialog" aria-modal="true" aria-label={`Detalle ${detail.id}`} onMouseDown={event => event.stopPropagation()}><button className="atlas-modal-close" onClick={close} aria-label="Cerrar"><X size={18}/></button><span>DETALLE DEL REGISTRO</span><h3>{detail.id}</h3><dl>{Object.entries(detail).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><button className="atlas-modal-primary" onClick={close}>Entendido</button></article></div>; }
