import type { Locale } from "../../i18n";

export type AtlasCopy = {
  meta: { title: string; description: string };
  nav: string[]; back: string; language: string; theme: string; dark: string; light: string; signature: string;
  hero: { eyebrow: string; title: string; copy: string; primary: string; secondary: string; demo: string };
  proof: string[]; sections: Record<string, { eyebrow: string; title: string; copy: string }>;
  modules: Array<[string, string]>; flow: Array<[string, string]>; governance: Array<[string, string]>; faq: Array<[string, string]>;
  cta: { title: string; copy: string; whatsapp: string; email: string };
};

export const atlasBiContent: Record<Locale, AtlasCopy> = {
  es: {
    meta: { title: "Atlas | Inteligencia empresarial bajo control", description: "Atlas centraliza dashboards empresariales, permisos, solicitudes y evidencia de acceso en una experiencia analítica de SOMA." },
    nav: ["Módulos", "Flujo", "Demo", "Gobierno", "Preguntas"], back: "Volver a SOMA", language: "Cambiar idioma", theme: "Cambiar tema", dark: "Modo oscuro", light: "Modo claro", signature: "Una solución de SOMA",
    hero: { eyebrow: "INTELIGENCIA EMPRESARIAL GOBERNADA", title: "Decisiones confiables, con el acceso correcto.", copy: "Atlas reúne los dashboards de su operación, controla quién los consulta y deja evidencia clara de cada solicitud, permiso y movimiento.", primary: "Solicitar demostración", secondary: "Escribir por correo", demo: "Explorar demo" },
    proof: ["Dashboards centralizados", "Permisos por alcance", "Solicitudes gestionadas", "Evidencia disponible"],
    sections: {
      modules: { eyebrow: "UNA VISTA CONECTADA", title: "La analítica que necesita, sin enlaces dispersos.", copy: "Atlas organiza recursos de análisis, sus responsables y su alcance para que cada equipo encuentre información útil con contexto y control." },
      flow: { eyebrow: "FLUJO DE ACCESO", title: "Publicar, habilitar y evidenciar en un mismo recorrido.", copy: "Cada dashboard conserva su alcance y cada decisión deja una huella que facilita el gobierno diario de la información." },
      demo: { eyebrow: "PRODUCTO EN ACCIÓN", title: "Explore el gobierno analítico de Atlas.", copy: "Demo frontend con datos ficticios. Simula catálogo, solicitudes, aprobaciones, roles y auditoría sin conectarse a sistemas externos." },
      governance: { eyebrow: "GOBIERNO CON CONTEXTO", title: "Visibilidad para decidir; límites para proteger.", copy: "La información se entrega según compañía, área y rol. Los equipos administradores conservan contexto para responder solicitudes con criterio." },
      faq: { eyebrow: "PREGUNTAS FRECUENTES", title: "Lo esencial antes de conectar sus reportes.", copy: "Atlas se adapta al catálogo y modelo de permisos de cada organización, con una experiencia clara para usuarios y administradores." },
    },
    modules: [["Biblioteca de dashboards", "Un catálogo único para encontrar recursos por área, compañía y estado de acceso."], ["Permisos", "Alcance por rol, compañía y unidad para entregar solo la información necesaria."], ["Solicitudes", "Las personas solicitan lectura o edición y el equipo responsable decide con contexto."], ["Auditoría", "Cada publicación, consulta, solicitud y decisión mantiene fecha, actor y recurso asociado."], ["Usuarios y roles", "Cobertura de acceso visible para administrar responsabilidades y privilegios mínimos."], ["Catálogos e integración", "Compañías, áreas y tipos de reporte organizados para una operación analítica consistente."]],
    flow: [["Publicar", "Registre el dashboard, su propietario y el alcance inicial."], ["Asignar", "Defina compañía, área y roles habilitados para el recurso."], ["Solicitar", "El usuario pide el nivel de acceso que necesita con su justificación."], ["Decidir", "El responsable aprueba o rechaza sin perder el contexto."], ["Evidenciar", "La auditoría conserva la actividad para consulta y control."]],
    governance: [["Alcance por organización", "Cada recurso puede responder a compañías, unidades o áreas específicas."], ["Privilegios mínimos", "Los roles separan consulta, administración y aprobación de solicitudes."], ["Gestión delegada", "Los responsables del negocio conservan autonomía dentro de un marco común."], ["Trazabilidad disponible", "La actividad queda organizada para revisar qué ocurrió y cuándo ocurrió."]],
    faq: [["¿Atlas reemplaza las herramientas de analítica?", "No. Atlas es la capa de acceso y gobierno que centraliza recursos de analítica ya existentes."], ["¿Podemos manejar dashboards restringidos?", "Sí. Un recurso restringido muestra la solicitud de acceso en lugar de exponer contenido sin autorización."], ["¿Cómo se definen los permisos?", "La configuración combina compañía, área, rol y el nivel de acceso que cada recurso requiere."], ["¿La demo guarda información?", "No. Funciona únicamente en el navegador con datos ficticios y se reinicia al recargar."], ["¿Se puede conectar con nuestro ERP?", "El producto está preparado para incorporar catálogos y usuarios desde los sistemas definidos en la implementación."]],
    cta: { title: "Haga visible la analítica correcta para cada decisión.", copy: "Cuéntenos cómo comparten hoy sus dashboards. Diseñaremos un recorrido Atlas alineado con sus roles, compañías y equipos.", whatsapp: "Solicitar por WhatsApp", email: "contacto@somacoretech.com" },
  },
  en: {
    meta: { title: "Atlas | Enterprise intelligence under control", description: "Atlas centralizes enterprise dashboards, permissions, requests and access evidence in a SOMA analytics experience." },
    nav: ["Modules", "Workflow", "Demo", "Governance", "Questions"], back: "Back to SOMA", language: "Change language", theme: "Change theme", dark: "Dark mode", light: "Light mode", signature: "A SOMA solution",
    hero: { eyebrow: "GOVERNED BUSINESS INTELLIGENCE", title: "Reliable decisions, with the right access.", copy: "Atlas brings operational dashboards together, controls who can consult them and preserves clear evidence for every request, permission and movement.", primary: "Request a demo", secondary: "Email us", demo: "Explore demo" },
    proof: ["Centralized dashboards", "Scope-based permissions", "Managed requests", "Available evidence"],
    sections: { modules: { eyebrow: "ONE CONNECTED VIEW", title: "The analytics you need, without scattered links.", copy: "Atlas organizes analytics resources, owners and scope so every team finds useful information with context and control." }, flow: { eyebrow: "ACCESS WORKFLOW", title: "Publish, enable and evidence in one journey.", copy: "Every dashboard retains its scope and every decision leaves a trace for daily information governance." }, demo: { eyebrow: "PRODUCT IN ACTION", title: "Explore Atlas analytics governance.", copy: "Frontend demo with fictional data. It simulates catalog, requests, approvals, roles and audit without connecting to external systems." }, governance: { eyebrow: "GOVERNANCE WITH CONTEXT", title: "Visibility to decide; boundaries to protect.", copy: "Information is delivered by company, area and role. Administrators retain context to decide requests with confidence." }, faq: { eyebrow: "FREQUENTLY ASKED QUESTIONS", title: "The essentials before connecting your reports.", copy: "Atlas adapts to every organization’s catalog and permission model with a clear experience for users and administrators." } },
    modules: [["Dashboard library", "One catalog to find resources by area, company and access status."], ["Permissions", "Scope by role, company and unit so only necessary information is delivered."], ["Requests", "People request reading or editing and the responsible team decides with context."], ["Audit", "Every publication, consultation, request and decision keeps an actor, date and resource."], ["Users and roles", "Visible access coverage to manage responsibilities and least-privilege access."], ["Catalogs and integration", "Companies, areas and report types organized for a consistent analytics operation."]],
    flow: [["Publish", "Register the dashboard, owner and initial scope."], ["Assign", "Define company, area and roles enabled for the resource."], ["Request", "The user asks for the access level they need with a reason."], ["Decide", "The owner approves or rejects without losing context."], ["Evidence", "Audit keeps activity available for control and review."]],
    governance: [["Organization scope", "Every resource can respond to specific companies, units or areas."], ["Least privilege", "Roles separate consultation, administration and request approval."], ["Delegated management", "Business owners retain autonomy within a shared governance framework."], ["Available traceability", "Activity is organized to review what happened and when it happened."]],
    faq: [["Does Atlas replace analytics tools?", "No. Atlas is the access and governance layer that centralizes existing analytics resources."], ["Can we manage restricted dashboards?", "Yes. A restricted resource shows an access request instead of exposing unauthorized content."], ["How are permissions defined?", "Configuration combines company, area, role and the access level required by each resource."], ["Does the demo save information?", "No. It runs only in the browser with fictional data and resets on refresh."], ["Can it connect to our ERP?", "The product is prepared to incorporate catalogs and users from the systems defined during implementation."]],
    cta: { title: "Make the right analytics visible for every decision.", copy: "Tell us how your dashboards are shared today. We will design an Atlas walkthrough aligned with your roles, companies and teams.", whatsapp: "Request on WhatsApp", email: "contacto@somacoretech.com" },
  },
};
