import {useEffect,useState} from'react';
import{ArrowRight,Bot,Boxes,Car,Code2,Database,HardHat,Menu,Scale,Search,ShieldCheck,X}from'lucide-react';
import{Analytics}from'@vercel/analytics/react';import CookieConsentBanner from'./components/CookieConsentBanner';import'./index.css';
const WA='https://wa.me/573185772152';
const products=[
 ['Atlas','Distribución segura de Power BI e iframes con permisos por usuario, grupos y autenticación corporativa.','Datos · Acceso · Power BI','/images/products/atlas.webp'],
 ['Orbit','ESM para tickets, PQRSF, activos y mantenimientos, con clasificación mediante IA y chatbots.','Servicio · Activos · IA','/images/products/orbit.webp'],
 ['Sonora','Creación de cuñas con IA y programación sincronizada de audio para todos los puntos de venta.','Audio · IA · Sincronización','/images/products/sonora.webp'],
 ['Flow','Solicitudes, órdenes de gasto y permisos de trabajo con solicitantes, aprobadores y supervisores.','Solicitudes · Aprobaciones · Control','/images/products/flow.webp'],
 ['Relay','Mensajería masiva y construcción de flujos de chatbot adaptados a cada operación.','Mensajería · Automatización · Chatbots','/images/products/relay.webp'],
]as const;
const development=[['SwitchU','Carpooling para conectar trayectos y movilizar comunidades.',Car],['LEXED','Inteligencia artificial aplicada a servicios legales.',Scale],['Civitas','Presupuestos de construcción desde las especificaciones del proyecto.',HardHat]]as const;
const capabilities=[['01','Estrategia y arquitectura','Definimos una ruta tecnológica coherente con la operación.',Boxes],['02','Software y productos digitales','Construimos plataformas seguras, escalables y mantenibles.',Code2],['03','Automatización e inteligencia artificial','Convertimos procesos y conocimiento en herramientas.',Bot],['04','Integración, datos e infraestructura','Conectamos sistemas, información y entornos tecnológicos.',Database],['05','Soporte y evolución','Acompañamos cada sistema durante su ciclo de vida.',ShieldCheck]]as const;
const sectors=[['Retail y comercio','Operación omnicanal, comunicaciones y experiencias consistentes en cada punto de venta.','https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1200&q=85'],['Servicios profesionales','Flujos, conocimiento y atención coordinados para equipos especializados.','https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85'],['Salud y atención','Información y procesos confiables para acompañar servicios sensibles.','https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=85'],['Operaciones internas','Control, trazabilidad y visibilidad sobre activos, solicitudes y logística.','https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85']]as const;
const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
function App(){const[menu,setMenu]=useState(false),[tab,setTab]=useState<'suite'|'landing'>('suite');useEffect(()=>{document.title='SOMA | Ingeniería digital para operaciones reales';document.documentElement.lang='es'},[]);const nav=[['Qué hacemos','capacidades'],['Soluciones','sectores'],['Productos','proyectos'],['Compañía','compania'],['Perspectivas','perspectivas']];return <div className="site"><Analytics/><header><div className="utility"><div className="container"><span>Bucaramanga, Colombia</span><span>Soporte &nbsp; | &nbsp; Contacto</span></div></div><div className="container nav"><button className="logo" onClick={()=>go('inicio')}><img src="/logo-light.svg" alt="SOMA"/></button><nav>{nav.map(([l,i])=><button key={i} onClick={()=>go(i)}>{l}</button>)}</nav><div className="nav-actions"><button className="search" aria-label="Buscar"><Search size={19}/></button><a className="btn primary nav-cta" href={WA}>Conversemos <ArrowRight size={17}/></a><button className="hamb" aria-label="Abrir menú" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div>{menu&&<div className="mobile-menu">{nav.map(([l,i])=><button key={i} onClick={()=>{go(i);setMenu(false)}}>{l}</button>)}</div>}</header><main>
<section id="inicio" className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Operaciones más fuertes</span><h1>Ingeniería digital para operaciones que no pueden detenerse.</h1><p>SOMA conecta estrategia, software, automatización e infraestructura para construir capacidades tecnológicas duraderas.</p><div className="actions"><a className="btn primary" href={WA}>Conversemos <ArrowRight size={18}/></a><button className="btn ghost" onClick={()=>go('proyectos')}>Explore productos <ArrowRight size={18}/></button></div></div><div className="hero-mark"><div className="mark-orbit"/><img src="/soma-bird-hd.webp" alt="Símbolo de SOMA"/><span>SISTEMAS · PERSONAS · OPERACIONES · RESULTADOS</span></div></div></section>
<section className="manifesto"><div className="container"><h2>Construimos sistemas, no piezas aisladas.</h2><p>Cada proyecto conecta procesos, datos y equipos para resolver una operación completa.</p></div></section>
<section id="proyectos" className="section projects"><div className="container"><Heading n="01" label="Productos" title="Una suite para operaciones reales." copy="Software funcional construido para integrar información, equipos y decisiones."/><div className="suite-tabs" role="tablist" aria-label="Portafolio"><button role="tab" aria-selected={tab==='suite'} className={tab==='suite'?'active':''} onClick={()=>setTab('suite')}>Nuestra suite <span>05</span></button><button role="tab" aria-selected={tab==='landing'} className={tab==='landing'?'active':''} onClick={()=>setTab('landing')}>Landing pages <span>04</span></button></div>
{tab==='suite'?<div className="suite-grid">{products.map(([name,desc,meta,img],i)=><article className={`suite-product ${i===0?'featured':''}`} key={name}><img src={img} alt={`Interfaz conceptual de ${name}`}/><div><div className="project-top"><h3>{name}</h3><Tag text="Funcional"/></div><p>{desc}</p><small>{meta}</small><Link/></div></article>)}</div>:<article className="landing-card"><div className="landing-mosaic">{[1,2,3,4].map(n=><img key={n} src={`/images/portfolio/portfolio${n}.webp`} alt="Landing page desarrollada por SOMA"/>)}</div><div><Tag text="Portafolio web"/><h3>Experiencias digitales que presentan, convierten y respaldan marcas.</h3><p>Diseño y desarrollo web enfocado en claridad, rendimiento y objetivos comerciales.</p><Link/></div></article>}
<div className="development-strip"><div><strong>En desarrollo</strong><span>Próximos productos de SOMA</span></div>{development.map(([name,desc,Icon])=><article key={name}><Icon/><div><strong>{name}</strong><span>{desc}</span></div></article>)}</div></div></section>
<section id="capacidades" className="section capabilities"><div className="container capabilities-grid"><Heading n="02" label="Capacidades" title="Capacidades que hacen posibles estos sistemas." copy="Un enfoque integral, desde la estrategia hasta la operación."/><div className="cap-list">{capabilities.map(([n,t,d,Icon])=><article key={n}><span>{n}</span><Icon/><div><h3>{t}</h3><p>{d}</p></div><ArrowRight/></article>)}</div></div></section>
<section id="sectores" className="section sectors"><div className="container"><Heading n="03" label="Sectores" title="Tecnología aplicada al contexto." copy="Cada imagen y cada solución representan el entorno operativo al que sirven."/><div className="sector-grid">{sectors.map(([t,d,i])=><article key={t}><img src={i} alt={t}/><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
<section id="compania" className="section process"><div className="container"><Heading n="04" label="Cómo trabajamos" title="Un socio tecnológico para construir y evolucionar." copy="Acompañamos su operación durante todo el ciclo de la solución."/><div className="steps">{[['01','Comprender'],['02','Definir'],['03','Construir'],['04','Acompañar']].map(([n,t])=><article key={n}><span>{n}</span><h3>{t}</h3><p>Decisiones con contexto, disciplina y foco en resultados.</p></article>)}</div><p className="statement">Combinamos entendimiento operativo, ingeniería de software y acompañamiento continuo.</p></div></section>
<section id="perspectivas" className="section insights"><div className="container"><Heading n="05" label="Perspectivas" title="Ideas para tomar mejores decisiones tecnológicas." copy="Criterios prácticos para construir tecnología útil."/><div className="insight-grid">{['Qué procesos vale la pena automatizar','Software propio frente a herramientas fragmentadas','Preparar los datos antes de adoptar IA'].map((t,i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>Análisis para tomar decisiones con mayor claridad.</p><Link/></article>)}</div></div></section><section id="contacto" className="cta"><div className="container"><div><h2>Construyamos el próximo sistema de su operación.</h2><p>Hablemos de sus desafíos y diseñemos una solución que genere valor real.</p></div><a className="btn primary" href={WA}>Hablar con SOMA <ArrowRight/></a></div></section></main>
<footer><div className="container footer-grid"><div className="footer-brand"><img src="/logo-dark.svg" alt="SOMA"/><p>Tecnología, personas y negocio para un futuro con más posibilidades.</p></div><Foot title="Qué hacemos" links={['Estrategia y arquitectura','Software y productos','Automatización e IA','Integración e infraestructura']}/><Foot title="Soluciones" links={['Retail y comercio','Servicios profesionales','Salud y atención','Operaciones internas']}/><Foot title="Compañía" links={['Nuestro enfoque','Productos','Contacto']}/></div><div className="container legal"><span>SOMA · Bucaramanga, Colombia · NIT 902080602-8</span><span><a href="/privacy.html">Privacidad</a> · <a href="/terms.html">Términos</a></span></div></footer><CookieConsentBanner/></div>}
function Heading({n,label,title,copy}:{n:string,label:string,title:string,copy:string}){return <div className="heading"><div><span>{n} / {label}</span><h2>{title}</h2></div><p>{copy}</p></div>}
function Tag({text}:{text:string}){return <span className="tag">{text}</span>}function Link(){return <a className="inline-link" href={WA}>Conocer el proyecto <ArrowRight size={16}/></a>}function Foot({title,links}:{title:string,links:string[]}){return <div className="foot"><h3>{title}</h3>{links.map(l=><a href="#inicio" key={l}>{l}</a>)}</div>}export default App;
