import { useMemo, useState } from "react";
import {
  ArrowLeftRight, Bell, Boxes, Building2, CalendarDays, ChevronLeft,
  ChevronRight, ClipboardList, Download, FileText, FolderOpen, History, Languages,
  Briefcase, Clock, Info, LayoutDashboard, MessageSquareDiff, Moon, Package, Plus,
  Search, Send, Settings2, UserRound, Wrench, X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { Locale } from "../../../i18n";
import { orbitDemoData, type DemoModule, type Ticket } from "../orbitDemoData";
import "./orbitDemo.css";

type Maintenance = (typeof orbitDemoData.maintenance)[number];
type Asset = (typeof orbitDemoData.assets)[number];
type Selection = Ticket | Maintenance | Asset;
type AppModule = DemoModule | "services" | "catalogs";

const moduleIcons: Record<AppModule, LucideIcon> = { dashboard: LayoutDashboard, incidents: FileText, pqrsf: MessageSquareDiff, maintenance: CalendarDays, assets: Boxes, services: Briefcase, catalogs: FolderOpen };
const assetTabs = [["Inventario", Boxes], ["Facturas", FileText], ["Traslados", ArrowLeftRight], ["Insumos", Package], ["Actas de entrega", ClipboardList], ["Proveedores", Building2]] as const;

export default function OrbitDemo({ locale }: { locale: Locale }) {
  const es = locale === "es";
  const [module, setModule] = useState<AppModule>("dashboard");
  const [selected, setSelected] = useState<Selection | null>(null);
  const [creating, setCreating] = useState(false);
  const [added, setAdded] = useState<Ticket[]>([]);
  const [query, setQuery] = useState("");
  const [queue, setQueue] = useState("all");
  const [notice, setNotice] = useState("");
  const labels: Record<AppModule, string> = { dashboard: "Dashboard", incidents: "Tickets", pqrsf: "PQRSF", maintenance: es ? "Cíclicos" : "Maintenance", assets: es ? "Activos" : "Assets", services: es ? "Otros servicios" : "Other services", catalogs: es ? "Catálogos" : "Catalogs" };
  const titles: Record<AppModule, string> = { dashboard: es ? "Bienvenido al dashboard" : "Welcome to the dashboard", incidents: "Tickets", pqrsf: "PQRSF", maintenance: es ? "Programación de mantenimientos cíclicos" : "Cyclic maintenance scheduling", assets: es ? "Gestión de activos fijos" : "Fixed asset management", services: es ? "Otros Servicios" : "Other Services", catalogs: es ? "Administración de catálogos" : "Catalog administration" };
  const tickets = useMemo(() => [...added, ...orbitDemoData.tickets].filter((ticket) => ticket.kind === module).filter((ticket) => queue === "all" || (queue === "urgent" ? ticket.priority !== "Media" : ticket.status !== "Cerrado")).filter((ticket) => `${ticket.id} ${ticket.title} ${ticket.area}`.toLowerCase().includes(query.toLowerCase())), [added, module, query, queue]);
  const changeModule = (next: AppModule) => { setModule(next); setQuery(""); setQueue("all"); setSelected(null); };

  return <div className="orbit-demo-shell"><div className="demo-layout">
    <aside className="demo-app-sidebar"><button className="demo-collapse" aria-label={es ? "Contraer menú" : "Collapse menu"}><ChevronLeft size={14}/></button><div className="demo-sidebar-logo"><img src="/orbit-fox-hd.webp" alt="Orbit"/><strong>ORBIT</strong></div><h3 className="demo-support-title">{es ? "Soporte" : "Support"}</h3><nav className="demo-nav" aria-label="Orbit demo modules">{(Object.keys(moduleIcons) as AppModule[]).map((name) => { const Icon = moduleIcons[name]; return <button key={name} aria-current={module === name ? "page" : undefined} onClick={() => changeModule(name)}><Icon size={22}/><span>{labels[name]}</span></button>; })}</nav><div className="demo-sidebar-user"><span>@</span><b>Sofía Moreno</b></div></aside>
    <div className="demo-app-body"><header className="demo-app-header"><span className="demo-breadcrumb">/ {labels[module]}</span><div><button aria-label={es ? "Idioma" : "Language"}><Languages size={22}/><small>{locale}</small></button><button aria-label={es ? "Tema" : "Theme"}><Moon size={22}/></button><button aria-label={es ? "Notificaciones" : "Notifications"}><Bell size={22}/><i/></button><button aria-label={es ? "Perfil" : "Profile"}><UserRound size={22}/></button></div></header><main className="demo-workspace"><div className="demo-page-heading"><h3>{titles[module]}</h3><span>{es ? "Demo con datos ficticios" : "Demo with sample data"}</span></div>{module === "dashboard" && <Dashboard es={es} onOpen={() => changeModule("incidents")}/>} {(module === "incidents" || module === "pqrsf") && <TicketWorkspace es={es} module={module} tickets={tickets} query={query} setQuery={setQuery} queue={queue} setQueue={setQueue} onCreate={() => setCreating(true)} onSelect={setSelected}/>} {module === "maintenance" && <MaintenanceWorkspace es={es} onSelect={setSelected}/>} {module === "assets" && <AssetsWorkspace es={es} onSelect={setSelected}/>} {module === "services" && <OtherServicesWorkspace es={es}/>} {module === "catalogs" && <CatalogWorkspace es={es}/>}</main></div>
  </div><div className="sr-only" aria-live="polite">{notice}</div>{(selected || creating) && <div className="demo-modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) { setSelected(null); setCreating(false); } }}><div className="demo-modal" role="dialog" aria-modal="true" tabIndex={-1}><button className="demo-close" autoFocus onClick={() => { setSelected(null); setCreating(false); }} aria-label={es ? "Cerrar" : "Close"}><X/></button>{creating ? <CreateForm es={es} onCancel={() => setCreating(false)} onCreate={(ticket) => { setAdded([ticket, ...added]); setCreating(false); setNotice(es ? "Ticket creado" : "Ticket created"); }}/> : selected && <Detail item={selected} es={es}/>}</div></div>}</div>;
}

function Dashboard({ es, onOpen }: { es: boolean; onOpen: () => void }) {
  const [dashboardTab, setDashboardTab] = useState("incidents");
  const metrics = [["Cumplimiento", "96.4%"], ["SLA", "91.8%"], ["IVT", "4.7 h"], ["Promedio de resolución", "7.2 h"]];
  const tabNames = [["incidents",es?"Incidencias":"Incidents"],["pqrsf","PQRSF"],["maintenance",es?"Mantenimientos":"Maintenance"],["assets",es?"Activos":"Assets"]];
  return <div className="demo-dashboard"><section className="demo-filter-bar dashboard-filter"><label>{es ? "Fecha inicial" : "Start date"}<input value="2026-09-01" readOnly/></label><label>{es ? "Fecha final" : "End date"}<input value="2026-09-30" readOnly/></label><label>{es ? "Prioridad" : "Priority"}<select><option>{es ? "Todas" : "All"}</option></select></label><button>{es ? "Aplicar filtros" : "Apply filters"}</button><button>{es ? "Limpiar" : "Clear"}</button></section><div className="demo-section-tabs">{tabNames.map(([key,label])=><button key={key} className={dashboardTab===key?"active":""} onClick={()=>setDashboardTab(key)}>{label}</button>)}</div><section className="demo-metric-grid">{metrics.map(([label, value],i) => <article key={label}><span>{dashboardTab === "incidents" ? label : `${label} · ${tabNames.find(([key])=>key===dashboardTab)?.[1]}`}</span><strong>{dashboardTab === "assets" ? ["342","18","7","COP 480M"][i] : dashboardTab === "maintenance" ? ["88%","24","6","3.1 h"][i] : value}</strong></article>)}</section><section className="demo-dashboard-grid"><article className="demo-chart"><h4>{es ? "Cumplimiento por día" : "Daily compliance"}</h4><p>{es ? "Comportamiento del periodo seleccionado" : "Selected-period performance"}</p><div className="line-chart"><svg viewBox="0 0 500 190" preserveAspectRatio="none"><path d="M0 150 C55 130 80 145 130 110 S210 62 270 90 S355 128 405 68 S465 48 500 30"/><path className="fill" d="M0 150 C55 130 80 145 130 110 S210 62 270 90 S355 128 405 68 S465 48 500 30 L500 190 L0 190Z"/></svg><div><span>L</span><span>M</span><span>X</span><span>J</span><span>V</span><span>S</span><span>D</span></div></div></article><article className="demo-ranking"><div><h4>{es ? "Tickets por usuario" : "Tickets by user"}</h4><button onClick={onOpen}>{es ? "Abrir tickets" : "Open tickets"}</button></div>{[["Laura Méndez",12],["Tomás Ríos",9],["Sofía Moreno",7]].map(([name,count],i)=><p key={String(name)}><small>#{i+1}</small><span>{name}</span><b>{count}</b></p>)}</article></section></div>;
}

function TicketWorkspace({ es, module, tickets, query, setQuery, queue, setQueue, onCreate, onSelect }: { es: boolean; module: DemoModule; tickets: Ticket[]; query: string; setQuery: (value: string) => void; queue: string; setQueue: (value: string) => void; onCreate: () => void; onSelect: (item: Ticket) => void }) {
  return <section className="demo-ticket-card"><header><div><h4>{module === "pqrsf" ? "PQRSF" : es ? "Incidencias" : "Incidents"}</h4><p>{es ? "Listado de tickets" : "Ticket list"}</p></div><div>{module !== "pqrsf" && <button onClick={onCreate}><Plus size={16}/>{es ? "Añadir registro" : "Add record"}</button>}<button><Download size={16}/>{es ? "Generar Excel" : "Export Excel"}</button></div></header><div className="demo-ticket-filters"><Field label={es ? "Prioridad" : "Priority"}/><Field label={es ? "Tipo" : "Type"}/><Field label={es ? "Estado" : "Status"}/><Field label={es ? "Usuario" : "User"}/><Field label={es ? "Sucursal" : "Location"}/><Field label={es ? "Orden" : "Order"}/><label className="search"><span>{es ? "Buscar" : "Search"}</span><div><Search size={15}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={es ? "Radicado o asunto" : "ID or subject"}/></div></label><button>{es ? "Buscar" : "Search"}</button><button>{es ? "Limpiar" : "Clear"}</button></div><div className="demo-queue-bar">{[["all",es?"Todos":"All"],["urgent",es?"Prioritarios":"Priority"],["open",es?"Abiertos":"Open"]].map(([value,label])=><button key={value} className={queue===value?"active":""} onClick={()=>setQueue(value)}>{label}<b>{value==="all"?tickets.length:value==="urgent"?2:3}</b></button>)}</div><div className="demo-table"><div className="demo-table-head"><span></span><span>Radicado</span><span>{es?"Tipo":"Type"}</span><span>{es?"Asunto":"Subject"}</span><span>{es?"Prioridad":"Priority"}</span><span>{es?"Estado":"Status"}</span><span>{es?"Responsable":"Owner"}</span><span></span></div>{tickets.map(ticket=><button key={ticket.id} onClick={()=>onSelect(ticket)}><input type="checkbox" onClick={(e)=>e.stopPropagation()}/><b>{ticket.id}</b><span>{module==="pqrsf"?"Solicitud":"Incidente"}</span><span>{ticket.title}</span><em className={`priority ${ticket.priority.toLowerCase().replace("í","i")}`}>{ticket.priority}</em><em>{ticket.status}</em><span>{ticket.owner}</span><ChevronRight size={16}/></button>)}</div><footer><span>{es ? `Mostrando ${tickets.length} registros` : `Showing ${tickets.length} records`}</span><div><button disabled><ChevronLeft size={15}/></button><b>1</b><button disabled><ChevronRight size={15}/></button></div></footer></section>;
}

function Field({ label }: { label: string }) { return <label><span>{label}</span><select><option>Todas</option></select></label>; }

function MaintenanceWorkspace({ es, onSelect }: { es: boolean; onSelect: (item: Maintenance) => void }) {
  const [maintenanceView, setMaintenanceView] = useState("planning");
  const [programOpen, setProgramOpen] = useState(false);
  const days = Array.from({length:35},(_,i)=>i<2?"":String(i-1));
  return <div className="demo-maintenance"><div className="demo-section-tabs"><button className={maintenanceView==="planning"?"active":""} onClick={()=>setMaintenanceView("planning")}><CalendarDays size={16}/>{es?"Planificación":"Planning"}</button><button className={maintenanceView==="history"?"active":""} onClick={()=>setMaintenanceView("history")}><History size={16}/>{es?"Historial":"History"}</button></div>{maintenanceView==="planning" ? <><section className="demo-calendar-card"><header><div><button><ChevronLeft size={16}/></button><button>Hoy</button><button><ChevronRight size={16}/></button><h4>Septiembre 2026</h4></div><div><button>Mes</button><button>Semana</button><button onClick={()=>setProgramOpen(true)}><Plus size={15}/> Programar</button></div></header><div className="demo-calendar-grid">{["LUN","MAR","MIÉ","JUE","VIE","SÁB","DOM"].map(day=><b key={day}>{day}</b>)}{days.map((day,i)=><button key={i}>{day}<span>{i===9?"Revisión preventiva":i===16?"Inspección eléctrica":""}</span></button>)}</div></section><div className="demo-cards">{orbitDemoData.maintenance.map(item=><button key={item.id} onClick={()=>onSelect(item)}><small>{item.date}</small><b>{item.title}</b><p>{item.site} · {item.owner}</p><em>{item.status}</em></button>)}</div></> : <HistoryTable es={es} onSelect={onSelect}/>} {programOpen && <MaintenanceForm es={es} onClose={()=>setProgramOpen(false)}/>}</div>;
}

function HistoryTable({ es, onSelect }: { es: boolean; onSelect: (item: Maintenance) => void }) {
  return <section className="demo-ticket-card"><header><div><h4>{es?"Historial de mantenimientos":"Maintenance history"}</h4><p>{es?"Ejecuciones, responsables y resultados":"Executions, owners and results"}</p></div><div><button><Download size={16}/>{es?"Exportar":"Export"}</button></div></header><div className="demo-table assets"><div className="demo-table-head"><span>ID</span><span>{es?"Mantenimiento":"Maintenance"}</span><span>{es?"Sede":"Site"}</span><span>{es?"Responsable":"Owner"}</span><span>{es?"Estado":"Status"}</span><span/></div>{orbitDemoData.maintenance.map(item=><button key={item.id} onClick={()=>onSelect(item)}><b>{item.id}</b><span>{item.title}</span><span>{item.site}</span><span>{item.owner}</span><em>{item.status}</em><ChevronRight size={16}/></button>)}</div></section>;
}

function MaintenanceForm({ es, onClose }: { es: boolean; onClose: () => void }) {
  return <div className="demo-modal-backdrop"><div className="demo-modal maintenance-form" role="dialog" aria-modal="true"><button className="demo-close" onClick={onClose}><X/></button><small>ORBIT / {es?"MANTENIMIENTOS":"MAINTENANCE"}</small><h3>{es?"Programar mantenimiento":"Schedule maintenance"}</h3><div className="modal-grid"><label>{es?"Empresa o sede":"Company or site"}<select><option>Sede Norte</option></select></label><label>{es?"Responsable":"Owner"}<select><option>Equipo técnico</option></select></label><label>{es?"Tipo":"Type"}<select><option>Preventivo</option><option>Correctivo</option></select></label><label>{es?"Fecha programada":"Scheduled date"}<input type="date" defaultValue="2026-09-24"/></label><label>{es?"Turno":"Shift"}<select><option>Mañana</option></select></label><label>{es?"Periodicidad":"Frequency"}<select><option>Mensual</option></select></label></div><label>{es?"Observaciones":"Notes"}<textarea rows={4}/></label><div className="form-actions"><button onClick={onClose}>{es?"Cancelar":"Cancel"}</button><button className="demo-primary" onClick={onClose}>{es?"Guardar programación":"Save schedule"}</button></div></div></div>;
}

function AssetsWorkspace({ es, onSelect }: { es: boolean; onSelect: (item: Asset) => void }) {
  const [assetTab, setAssetTab] = useState(0);
  const [createOpen, setCreateOpen] = useState(false);
  const tabName = assetTabs[assetTab][0];
  return <div className="demo-assets"><div className="demo-asset-tabs">{assetTabs.map(([name,Icon],i)=><button key={name} className={i===assetTab?"active":""} onClick={()=>setAssetTab(i)}><Icon size={16}/>{name}</button>)}</div><section className="demo-ticket-card"><header><div><h4>{assetTab===0?(es?"Inventario de activos":"Asset inventory"):tabName}</h4><p>{assetTab===0?(es?"Consulta y administración de activos fijos":"Fixed asset administration"):(es?`Gestión de ${tabName.toLowerCase()}`:`${tabName} management`)}</p></div><div><button onClick={()=>setCreateOpen(true)}><Plus size={16}/>{assetTab===0?(es?"Crear activo":"Create asset"):(es?"Añadir registro":"Add record")}</button><button><Download size={16}/>{es?"Exportar":"Export"}</button></div></header><div className="demo-ticket-filters asset"><Field label={es?"Categoría":"Category"}/><Field label={es?"Ubicación":"Location"}/><Field label={es?"Estado":"Status"}/><label className="search"><span>{es?"Buscar":"Search"}</span><div><Search size={15}/><input placeholder={es?"Código o nombre":"Code or name"}/></div></label><button>{es?"Buscar":"Search"}</button></div>{assetTab===0?<div className="demo-table assets"><div className="demo-table-head"><span>Código</span><span>{es?"Activo":"Asset"}</span><span>{es?"Categoría":"Category"}</span><span>{es?"Ubicación":"Location"}</span><span>{es?"Estado":"Status"}</span><span></span></div>{orbitDemoData.assets.map(item=><button key={item.id} onClick={()=>onSelect(item)}><b>{item.id}</b><span>{item.name}</span><span>{item.category}</span><span>{item.site}</span><em>{item.status}</em><ChevronRight size={16}/></button>)}</div>:<AssetSubtable tab={tabName} es={es}/>}</section>{createOpen&&<AssetCreateForm tab={tabName} es={es} onClose={()=>setCreateOpen(false)}/>}</div>;
}

function AssetSubtable({ tab, es }: { tab: string; es: boolean }) {
  const rows: Record<string,string[][]> = { Facturas:[["FAC-0184","Tecnología Andina","COP 8.420.000","18 SEP 2026"],["FAC-0179","Equipos del Norte","COP 3.180.000","03 SEP 2026"]], Traslados:[["TR-0281","Sede Centro","Centro logístico","Completado"],["TR-0276","Sede Norte","Sede Centro","En tránsito"]], Insumos:[["INS-0042","Cable UTP Cat 6","84 unidades","Disponible"],["INS-0038","Tóner impresora","12 unidades","Bajo stock"]], "Actas de entrega":[["ACTA-0162","Laura Méndez","Portátil Dell Latitude","Firmada"],["ACTA-0159","Tomás Ríos","Terminal TX-4","Pendiente"]], Proveedores:[["PRV-014","Tecnología Andina","contacto@proveedor.co","Activo"],["PRV-008","Equipos del Norte","ventas@equipos.co","Activo"]] };
  return <div className="demo-generic-table"><div><b>{es?"Código":"Code"}</b><b>{es?"Descripción":"Description"}</b><b>{es?"Detalle":"Detail"}</b><b>{es?"Estado":"Status"}</b></div>{(rows[tab]||[]).map(row=><button key={row[0]}>{row.map(cell=><span key={cell}>{cell}</span>)}</button>)}</div>;
}

function AssetCreateForm({ tab, es, onClose }: { tab: string; es: boolean; onClose: () => void }) {
  return <div className="demo-modal-backdrop"><div className="demo-modal" role="dialog" aria-modal="true"><button className="demo-close" onClick={onClose}><X/></button><small>ORBIT / {tab.toUpperCase()}</small><h3>{es?`Crear ${tab.toLowerCase()}`:`Create ${tab}`}</h3><div className="modal-grid"><label>{es?"Nombre o número":"Name or number"}<input/></label><label>{es?"Categoría":"Category"}<select><option>Tecnología</option></select></label><label>{es?"Empresa o sede":"Company or site"}<select><option>Sede Norte</option></select></label><label>{es?"Responsable":"Owner"}<select><option>Operaciones</option></select></label></div><label>{es?"Notas":"Notes"}<textarea rows={4}/></label><div className="form-actions"><button onClick={onClose}>{es?"Cancelar":"Cancel"}</button><button className="demo-primary" onClick={onClose}>{es?"Guardar":"Save"}</button></div></div></div>;
}

function CatalogWorkspace({ es }: { es: boolean }) {
  const tabs = ["Usuarios","Roles y categorías","Prioridades","Estados","Razones de pausa","CO","Checklist","Plantillas","Unidades insumos","Otros servicios","Permisos","Configuración"];
  const [catalogTab, setCatalogTab] = useState("Roles y categorías");
  return <div className="demo-catalogs"><div className="demo-asset-tabs">{tabs.map(name=><button key={name} className={catalogTab===name?"active":""} onClick={()=>setCatalogTab(name)}><Settings2 size={15}/>{name}</button>)}</div><section className="demo-ticket-card"><header><div><h4>{catalogTab}</h4><p>{es?"Configuración maestra de Orbit":"Orbit master configuration"}</p></div><div><button><Plus size={16}/>{es?"Añadir registro":"Add record"}</button></div></header><div className="demo-generic-table"><div><b>{es?"Nombre":"Name"}</b><b>{es?"Descripción":"Description"}</b><b>{es?"Estado":"Status"}</b><b>{es?"Acciones":"Actions"}</b></div>{[["Operaciones","Gestión operativa y soporte","Activo","Editar"],["Infraestructura","Equipos, red y plataformas","Activo","Editar"],["Servicio","Atención de solicitudes","Activo","Editar"]].map(row=><button key={row[0]}>{row.map(cell=><span key={cell}>{cell}</span>)}</button>)}</div></section></div>;
}

function OtherServicesWorkspace({ es }: { es: boolean }) {
  const [serviceTab, setServiceTab] = useState("Monitoreo");
  return <div><div className="demo-section-tabs">{["Monitoreo","Reportes","Operación"].map(name=><button key={name} className={serviceTab===name?"active":""} onClick={()=>setServiceTab(name)}><Briefcase size={15}/>{name}</button>)}</div><section className="demo-service-frame"><header><div><h4>{serviceTab}</h4><p>{es?"Servicio integrado mediante iframe seguro":"Service embedded through a secure iframe"}</p></div><button>{es?"Abrir aparte":"Open separately"}</button></header><div><MonitorCard/><MonitorCard second/></div></section></div>;
}

function MonitorCard({ second=false }: { second?: boolean }) { return <article><span>{second?"API / Gateway":"Core / ERP"}</span><strong>{second?"99.92%":"99.98%"}</strong><small>UP · 24 h</small></article>; }

function CreateForm({ es, onCancel, onCreate }: { es: boolean; onCancel: () => void; onCreate: (ticket: Ticket) => void }) {
  return <form onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);onCreate({id:"INC-1049",title:String(data.get("title")),kind:"incidents",area:String(data.get("area")),priority:String(data.get("priority")) as Ticket["priority"],status:"Nuevo",sla:"04:00",owner:"Mesa de servicio",created:"Ahora"});}}><small>ORBIT / TICKETS</small><h3>{es?"Añadir registro":"Add record"}</h3><label>{es?"Asunto":"Subject"}<input name="title" required/></label><label>{es?"Área":"Area"}<select name="area"><option>Operaciones</option><option>Infraestructura</option></select></label><label>{es?"Prioridad":"Priority"}<select name="priority"><option>Media</option><option>Alta</option><option>Crítica</option></select></label><div className="form-actions"><button type="button" onClick={onCancel}>{es?"Cancelar":"Cancel"}</button><button className="demo-primary" type="submit">{es?"Guardar":"Save"}</button></div></form>;
}

function Detail({ item, es }: { item: Selection; es: boolean }) {
  if ("category" in item) return <AssetDetail item={item} es={es}/>;
  if (item.id.startsWith("MNT")) return <MaintenanceDetail item={item as Maintenance} es={es}/>;
  return <TicketDetail item={item as Ticket} es={es}/>;
}

function TicketDetail({ item, es }: { item: Ticket; es: boolean }) {
  const [ticketTab, setTicketTab] = useState("detail");
  const ticketTabs: Array<[string,string,LucideIcon]> = [["detail",es?"Detalle del caso":"Case details",Info],["chat",es?"Conversación":"Conversation",MessageSquareDiff],["timeline",es?"Trazabilidad":"History",Clock]];
  return <div className="demo-detail wide-detail"><small>ORBIT / {item.id}</small><h3>{item.title}</h3><div className="modal-tabs">{ticketTabs.map(([key,label,Icon])=><button key={key} className={ticketTab===key?"active":""} onClick={()=>setTicketTab(key)}><Icon size={15}/>{label}</button>)}</div>{ticketTab==="detail"&&<><div className="detail-meta"><span><b>{es?"Estado":"Status"}</b>{item.status}</span><span><b>{es?"Responsable":"Owner"}</b>{item.owner}</span><span><b>{es?"Prioridad":"Priority"}</b>{item.priority}</span><span><b>{es?"Área":"Area"}</b>{item.area}</span></div><section><h4>{es?"Descripción":"Description"}</h4><p>{es?"El usuario reporta una incidencia que afecta la continuidad de la operación.":"The user reports an incident affecting operations."}</p></section></>}{ticketTab==="chat"&&<section className="demo-chat"><p className="customer"><b>Solicitante</b>{es?"El equipo presenta intermitencia desde esta mañana.":"The equipment has been intermittent since this morning."}</p><p className="agent"><b>{item.owner}</b>{es?"Estamos validando conectividad y registros del terminal.":"We are checking connectivity and terminal logs."}</p><label><textarea placeholder={es?"Escribe una respuesta…":"Write a reply…"}/><button><Send size={16}/>{es?"Responder":"Reply"}</button></label></section>}{ticketTab==="timeline"&&<section className="demo-timeline"><p><b>09:04</b>{es?"Asignado al equipo responsable":"Assigned to responsible team"}</p><p><b>08:42</b>{es?"Clasificación automática confirmada":"Automatic classification confirmed"}</p><p><b>08:21</b>{es?"Ticket creado desde WhatsApp":"Ticket created from WhatsApp"}</p></section>}</div>;
}

function AssetDetail({ item, es }: { item: Asset; es: boolean }) {
  const [assetDetailTab, setAssetDetailTab] = useState("Información");
  const tabs=[["Información",Package],["Factura",FileText],["Mantenimientos",Wrench],["Traslados",ArrowLeftRight]] as const;
  return <div className="demo-detail wide-detail"><small>ORBIT / {item.id}</small><h3>{item.name}</h3><div className="modal-tabs">{tabs.map(([name,Icon])=><button key={name} className={assetDetailTab===name?"active":""} onClick={()=>setAssetDetailTab(name)}><Icon size={15}/>{name}</button>)}</div>{assetDetailTab==="Información"&&<div className="detail-meta"><span><b>{es?"Estado":"Status"}</b>{item.status}</span><span><b>{es?"Responsable":"Owner"}</b>{item.owner}</span><span><b>{es?"Categoría":"Category"}</b>{item.category}</span><span><b>{es?"Ubicación":"Location"}</b>{item.site}</span></div>}{assetDetailTab==="Factura"&&<section className="document-preview"><FileText size={34}/><b>FAC-2026-0184.pdf</b><span>{es?"Factura asociada al activo":"Invoice linked to asset"}</span></section>}{assetDetailTab==="Mantenimientos"&&<section className="demo-timeline"><p><b>18 AGO</b>{es?"Revisión preventiva completada":"Preventive inspection completed"}</p><p><b>03 JUN</b>{es?"Limpieza y prueba funcional":"Cleaning and functional test"}</p></section>}{assetDetailTab==="Traslados"&&<section className="demo-timeline"><p><b>12 SEP</b>{es?`Asignado a ${item.owner}`:`Assigned to ${item.owner}`}</p><p><b>03 JUN</b>{es?`Recibido en ${item.site}`:`Received at ${item.site}`}</p></section>}</div>;
}

function MaintenanceDetail({ item, es }: { item: Maintenance; es: boolean }) {
  return <div className="demo-detail wide-detail"><small>ORBIT / {item.id}</small><h3>{item.title}</h3><div className="detail-meta"><span><b>{es?"Estado":"Status"}</b>{item.status}</span><span><b>{es?"Responsable":"Owner"}</b>{item.owner}</span><span><b>{es?"Sede":"Site"}</b>{item.site}</span><span><b>{es?"Progreso":"Progress"}</b>{item.progress}%</span></div><section><h4>Checklist</h4><p>✓ {es?"Inspección visual":"Visual inspection"}</p><p>✓ {es?"Prueba funcional":"Functional test"}</p><p>○ {es?"Registro de evidencias":"Evidence record"}</p></section><section><h4>{es?"Firmas":"Signatures"}</h4><p>{es?"Responsable técnico · pendiente":"Technical owner · pending"}</p></section></div>;
}
