import { useMemo, useState } from "react";
import { BarChart3, Bell, BookOpen, Building2, ChevronRight, FileCheck2, Menu, Search, ShieldCheck, X } from "lucide-react";
import type { Locale } from "../../../i18n";
import { atlasAudit, atlasReports, atlasRequests, type AccessRequest, type AtlasModule, type AtlasReport } from "../atlasBiDemoData";
import "./atlasBiDemo.css";

const nav: Array<[AtlasModule, string, typeof BarChart3]> = [["home", "Inicio", Building2], ["dashboards", "Dashboards", BarChart3], ["requests", "Administración", FileCheck2], ["audit", "Auditoría", ShieldCheck], ["catalogs", "Catálogos", BookOpen]];

export default function AtlasBiDemo({ locale }: { locale: Locale }) {
  const [module, setModule] = useState<AtlasModule>("home"); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("Todas"); const [detail, setDetail] = useState<AtlasReport | null>(null); const [mobileOpen, setMobileOpen] = useState(false); const [dark, setDark] = useState(false); const [notice, setNotice] = useState(""); const [requests, setRequests] = useState(atlasRequests);
  const reports = useMemo(() => atlasReports.filter(item => `${item.title} ${item.area} ${item.company}`.toLowerCase().includes(query.toLowerCase()) && (filter === "Todas" || item.area === filter)), [query, filter]);
  const change = (next: AtlasModule) => { setModule(next); setMobileOpen(false); setNotice(`${nav.find(([id]) => id === next)?.[1]} abierto`); };
  const approveRequest = (id: string) => { setRequests(items => items.map(item => item.id === id ? { ...item, status: "Aprobada" } : item)); setNotice("Solicitud aprobada"); };
  const rejectRequest = (id: string) => { setRequests(items => items.map(item => item.id === id ? { ...item, status: "Rechazada" } : item)); setNotice("Solicitud rechazada"); };
  const createAccessRequest = (report: AtlasReport) => { setRequests(items => [{ id: `SOL-${129 + items.length}`, report: report.title, requester: "Andrea Morales", level: "Lectura", status: "Pendiente", date: "Ahora" }, ...items]); setDetail(null); setModule("requests"); setNotice("Solicitud de acceso creada"); };
  const title = nav.find(([id]) => id === module)?.[1] ?? "Inicio";
  return <div className={`atlas-bi-demo ${dark ? "dark" : ""}`}><div className="atlas-bi-note"><span>{locale === "es" ? "Entorno demostrativo · Datos ficticios" : "Demo environment · Fictional data"}</span><button onClick={() => { setModule("home"); setQuery(""); setFilter("Todas"); setNotice("Demo reiniciada"); }}>{locale === "es" ? "Reiniciar" : "Reset"}</button></div><div className="atlas-bi-app"><aside className={`atlas-bi-side ${mobileOpen ? "open" : ""}`}><div className="atlas-bi-logo"><img src="/atlas-owl-hd.webp" alt=""/><span>ATLAS<small>ANALYTICS GOVERNANCE</small></span><button className="atlas-bi-close-nav" aria-label="Cerrar navegación" onClick={() => setMobileOpen(false)}><X size={17}/></button></div><nav aria-label="Navegación Atlas">{nav.map(([id, label, Icon]) => <button key={id} className={module === id ? "active" : ""} onClick={() => change(id)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="atlas-bi-side-footer">SOMA · Organización demo</div></aside>{mobileOpen && <button className="atlas-bi-backdrop" aria-label="Cerrar navegación" onClick={() => setMobileOpen(false)}/>}<section className="atlas-bi-main"><header className="atlas-bi-header"><button className="atlas-bi-mobile-menu" aria-label="Abrir navegación" onClick={() => setMobileOpen(true)}><Menu size={20}/></button><div><p>Atlas / {title}</p><h3>{module === "home" ? (locale === "es" ? "Resumen analítico" : "Analytics overview") : title}</h3></div><div className="atlas-bi-actions"><button onClick={() => setDark(!dark)}>{dark ? "Claro" : "Oscuro"}</button><button aria-label="Notificaciones"><Bell size={17}/></button><span>AM</span></div></header><div className="atlas-bi-content" aria-live="polite">{notice && <p className="atlas-demo-live">{notice}</p>}{module === "home" ? <Home onDashboards={() => change("dashboards")}/> : module === "dashboards" ? <Dashboards reports={reports} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} open={setDetail}/> : module === "requests" ? <Requests rows={requests} approve={approveRequest} reject={rejectRequest}/> : module === "audit" ? <Audit/> : <Catalogs/>}</div></section></div>{detail && <ReportModal report={detail} close={() => setDetail(null)} request={createAccessRequest} />}</div>;
}
function Home({ onDashboards }: { onDashboards: () => void }) { return <><div className="atlas-bi-metrics"><Metric label="Dashboards activos" value="24" detail="4 actualizados hoy"/><Metric label="Solicitudes abiertas" value="08" detail="2 requieren decisión"/><Metric label="Accesos controlados" value="99.2%" detail="+0.4 este mes"/><Metric label="Cobertura de roles" value="06" detail="Roles configurados"/></div><div className="atlas-bi-grid"><article className="atlas-bi-card atlas-bi-activity"><header><h4>Actividad reciente</h4><button onClick={onDashboards}>Ver dashboards <ChevronRight size={14}/></button></header>{["Dashboard publicado · Operaciones KPI", "Solicitud enviada · Nivel de servicio", "Permiso actualizado · Ventas nacional"].map((item, index) => <p key={item}><span>0{index + 1}</span>{item}<small>{index === 0 ? "Hace 12 min" : "Hoy"}</small></p>)}</article><article className="atlas-bi-card atlas-bi-status"><span>CONTROL DE ACCESO</span><strong>Todo bajo control</strong><p>Los recursos analíticos mantienen responsables, alcance y actividad verificable.</p><div><i/><i/><i/><i/><i/></div></article></div></>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function Dashboards({ reports, query, setQuery, filter, setFilter, open }: { reports: AtlasReport[]; query: string; setQuery: (value: string) => void; filter: string; setFilter: (value: string) => void; open: (report: AtlasReport) => void }) { return <><div className="atlas-bi-toolbar"><label className="atlas-bi-search"><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar dashboard, área o compañía"/></label><select className="atlas-bi-filter" value={filter} onChange={event => setFilter(event.target.value)}><option>Todas</option><option>Comercial</option><option>Operaciones</option><option>Finanzas</option><option>Talento</option></select></div>{reports.length ? <div className="atlas-bi-report-grid">{reports.map(report => <button className="atlas-bi-card atlas-bi-report" key={report.id} onClick={() => open(report)}><span className={`atlas-bi-badge ${report.status === "Restringido" ? "restricted" : ""}`}>{report.status}</span><h4>{report.title}</h4><p>{report.description}</p><footer><span>{report.company}</span><span>{report.updated}</span></footer></button>)}</div> : <div className="atlas-bi-empty"><Search size={28}/><h4>No hay resultados para esta búsqueda.</h4><p>Pruebe otro término o restablezca el filtro.</p></div>}</>; }
function Requests({ rows, approve, reject }: { rows: AccessRequest[]; approve: (id: string) => void; reject: (id: string) => void }) { return <div className="atlas-bi-table"><h4>Solicitudes de acceso</h4><p>Decida cada solicitud sin perder el recurso, nivel y solicitante.</p>{rows.map(row => <article key={row.id}><div><b>{row.report}</b><span>{row.id} · {row.requester} · {row.level} · {row.date}</span></div><em className={row.status.toLowerCase()}>{row.status}</em>{row.status === "Pendiente" && <div className="atlas-bi-row-actions"><button onClick={() => approve(row.id)}>Aprobar</button><button onClick={() => reject(row.id)}>Rechazar</button></div>}</article>)}</div>; }
function Audit() { return <div className="atlas-bi-table"><h4>Auditoría</h4><p>Actividad asociada a actor, recurso, fecha e IP.</p>{atlasAudit.map(item => <article key={item.id}><div><b>{item.action}</b><span>{item.actor} · {item.resource} · {item.date}</span></div><em>{item.ip}</em></article>)}</div>; }
function Catalogs() { return <div className="atlas-bi-catalogs">{[["Compañías", "SOMA Colombia · SOMA Servicios"], ["Áreas", "Comercial · Operaciones · Finanzas · Talento"], ["Tipos de reporte", "Operativo · Financiero · Estratégico"]].map(([title, copy], index) => <article className="atlas-bi-card" key={title}><span>0{index + 1}</span><h4>{title}</h4><p>{copy}</p></article>)}</div>; }
function ReportModal({ report, close, request }: { report: AtlasReport; close: () => void; request: (report: AtlasReport) => void }) { const restricted = report.status === "Restringido"; return <div className="atlas-bi-modal-backdrop" role="presentation" onMouseDown={close}><article className="atlas-bi-modal" role="dialog" aria-modal="true" aria-label={`Detalle ${report.title}`} onMouseDown={event => event.stopPropagation()}><button className="atlas-bi-modal-close" onClick={close} aria-label="Cerrar"><X size={19}/></button><span>DETALLE DEL DASHBOARD</span><h3>{report.title}</h3><p>{restricted ? "Este dashboard es restringido. Solicite acceso para continuar." : report.description}</p><dl><div><dt>Área</dt><dd>{report.area}</dd></div><div><dt>Compañía</dt><dd>{report.company}</dd></div><div><dt>Responsable</dt><dd>{report.owner}</dd></div><div><dt>Estado</dt><dd>{report.status}</dd></div></dl><button className="atlas-bi-primary" onClick={() => restricted ? request(report) : close()}>{restricted ? "Solicitar acceso" : "Abrir dashboard"}</button></article></div>; }
